name: Selenium with TestNG - CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@1.2.0

      - name: Download Chromedriver
        run: sudo apt-get install -y chromium-chromedriver

      - name: Set up display for browser tests
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 & export DISPLAY=:99

      - name: Verify Chrome version
        run: chrome --version

      - name: List directory contents
        run: ls -R

      - name: Build with Maven
        run: mvn -B clean test --errors
